name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: All things angular
    uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.3.2
    with:
      angular_project_dir: ./rock-paper-scissors-frontend
      github_access_token: ${{ secrets.ACCESS_TOKEN }}
      build_configuration: production
      base_href: https://straykerpl.github.io/rock-paper-scissors/
      deploy_branch: test-env