name: Deploy Test Environment

env:
  NODE_VERSION: "18.x"
  FRONTEND_PATH: "rock-paper-scissors-frontend"

on:
  pull_request:
    types: [closed]
    branches: develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.FRONTEND_PATH }}/package-lock.json
      - run: npm ci --prefix ${{ env.FRONTEND_PATH }}
      - run: npm run prod-gh-pages-build --prefix ${{ env.FRONTEND_PATH }} --if-present
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '${{ env.FRONTEND_PATH }}/dist/${{ env.FRONTEND_PATH }}'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
