name: Build and Deploy
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Deploy on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          angular_project_dir: ./rock-paper-scissors-frontend
          angular_dist_build_folder: ./rock-paper-scissors-frontend/dist/rock-paper-scissors-frontend
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          build_configuration: production
          base_href: https://straykerpl.github.io/RockPaperScissors/
          deploy_branch: main
